spring.application.name=user-service
spring.docker.compose.enabled=false
server.port=8088
# 1. Fixed host (using the fallback trick) and fixed DB name (userDB)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/userDB

spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.hostname=user-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/