spring.application.name=user-service
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://user-db:5432/user_db
spring.datasource.username=account_user
spring.datasource.password=account_pass

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect