services:
  user-db:
    image: postgres
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_user
      POSTGRES_PASSWORD: user_pass
    volumes: ["user_pgdata:/var/lib/postgresql"]

  account-db:
    image: postgres
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_pass
    volumes: ["account_pgdata:/var/lib/postgresql"]

  transaction-db:
    image: postgres
    environment:
      POSTGRES_DB: transaction_db
      POSTGRES_USER: transaction_user
      POSTGRES_PASSWORD: transaction_pass
    volumes: ["transaction_pgdata:/var/lib/postgresql"]

  logging-db:
    image: postgres
    environment:
      POSTGRES_DB: logging_db
      POSTGRES_USER: logging_user
      POSTGRES_PASSWORD: logging_pass
    volumes: [ "logging_pgdata:/var/lib/postgresql" ]

  account-service:
    build: ./services/account-service
    depends_on: [account-db]
    ports: ["8081:8080"]

  logging-service:
    build: ./services/logging-service
    depends_on: [logging-db]
    ports: ["8085:8080"]

  kafka-server:
    image: apache/kafka:latest
    container_name: vbank-kafka
    hostname: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      CLUSTER_ID: "xXFeO7HWRveirWAPPAKrGw"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - 8073:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: vbank
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: 'true'
      SWAGGER_UI_ENABLED: 'true'
    volumes:
      - kafka-ui:/var/lib/kafka/ui


volumes:
  user_pgdata:
  account_pgdata:
  transaction_pgdata:
  logging_pgdata:
  kafka-data:
  kafka-ui: