server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: bff-service

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://user-service:8088/.well-known/jwks.json
eureka:
  instance:
    hostname: bff-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
