server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: bff-service

eureka:
  instance:
    hostname: bff-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
