server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: logging-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:logging-db}:${DB_PORT:5432}/${DB_NAME:logging_db}
    username: ${DB_USER:logging_user}
    password: ${DB_PASS:logging_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-server:9092}

    consumer:
      group-id: microservices-logs
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.value.default.type: com.ejadainternship.vbank.logging_service.dtos.LogItemDTO
        spring.json.use.type.headers: false

  eureka:
    instance:
      hostname: logging-service
      prefer-ip-address: true
    client:
      service-url:
        defaultZone: http://${EUREKA_HOST:service-registry}:${EUREKA_PORT:8761}/eureka/
