spring:
  application:
    name: logging-service
  datasource:
    # Changed host to localhost and DB name to loggingDB
    url: jdbc:postgresql://localhost:5440/loggingDB
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    # Assuming Kafka is also mapped to localhost
    bootstrap-servers: localhost:9092

    consumer:
      group-id: microservices-logs
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.value.default.type: com.ejadainternship.vbank.logging_service.dtos.LogItemDTO
        spring.json.use.type.headers: false