spring.application.name=transaction-service
server.port=${SERVER_PORT:8089}
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:transactionDB}
spring.datasource.username=${DB_USER:admin}
spring.datasource.password=${DB_PASS:password}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.hostname=transaction-service
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
