spring.application.name=transaction-service
server.port=${SERVER_PORT:8089}
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://${DB_HOST:transaction-db}:${DB_PORT:5432}/${DB_NAME:transaction_db}
spring.datasource.username=${DB_USER:transaction_user}
spring.datasource.password=${DB_PASS:transaction_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.hostname=transaction-service
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://${EUREKA_HOST:service-registry}:${EUREKA_PORT:8761}/eureka/
