spring.application.name=transaction-service
server.port=8089
spring.docker.compose.enabled=false


spring.datasource.url=jdbc:postgresql://localhost:5432/transactionDB
spring.datasource.username=admin
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

eureka.instance.hostname= transaction-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/