version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_transactionDB
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: transactionDB
    ports:
      - "5435:5432"
    volumes:
      - pg_transaction_data:/var/lib/postgresql

volumes:
  pg_transaction_data: