server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5438}/${DB_NAME:accountsDB}
    username: ${DB_USER:admin}
    password: ${DB_PASS:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  logging:
    level:
      feign: DEBUG
      com.netflix.loadbalancer: DEBUG
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://user-service:8088/.well-known/jwks.json
account:
  number-generation-service:
    max-attempts: 10

eureka:
  instance:
    hostname: account-service
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/