spring:
  application:
    name: account-service
  datasource:
    url: jdbc:postgresql://account-db:5432/account_db
    username: account_user
    password: account_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: kafka-server:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

account:
  number-generation-service:
    max-attempts: 10